module.exports = {
    en: {
        image1: "./src/assets/images/WoodHouse.jpg",
        imageDescription1: "A modern wooden house",
        title: "Company",
        subTitle: "After more than ten years of experience in the field of independent real estate appraisals, Mrs Barbara Progin founded “e2i expertises immobilières indépendantes Sàrl” in July 2012.",
        section1Title: "Field of activity",
        section1Item1: "The company provides various services related to appraisals, estimates, analysis and advice in the real estate sector and in the field of training in independent real estate appraisals.",
        section1Item2: "We carry all types of independent real estate appraisals, whether to estimate a villa, a lot PPE, a building, a vacant land, a DDP or some other easements.",
        section1Item3: "The company, through Barbara Progin, is also active in the field of training in independent real estate appraisals including at HEC Lausanne (3rd year bachelor in management) and at the USPI (certificate of real estate appraiser).",
        section1Item4: "Independent work is essential for us, the company does not participate in any brokerage activity or promotion, which allows us to avoid conflicts of interest and guarantee our clients a perfect neutrality and integrity.",
        section1Item5: "Because independence of work is paramount to us, the company is not involved in any brokerage or promotional activities, which enables us to avoid conflicts of interest and guarantee our customers total neutrality and integrity.",
        section2Title: "Area of activity",
        section2Item1: "We carry out independent appraisals for properties essentially in Western Switzerland (Suisse romande) and particularly in the canton of Vaud.",
        section2Item2: "We also carry out more specific real estate appraisals in the cantons of Valais, Bern, Fribourg and Neuchâtel.",
        image2: "./src/assets/images/Kitchen.jpg",
        imageDescription2: "A modern kitchen",
        namespace: "services",
    },
    fr: {
        image1: "./src/assets/images/WoodHouse.jpg",
        imageDescription1: "Une maison moderne en bois",
        title: "Société",
        subTitle: "Après une dizaine d’années d’expérience dans le domaine de l’estimation immobilière, Mme Barbara Progin a fondé la société « e2i expertises immobilières indépendantes Sàrl » en juillet 2012.",
        section1Title: "Domaine d’activité",
        section1Item1: "La société a pour but toutes activités en lien avec l’expertise, l’estimation, l’analyse et le conseil dans le secteur immobilier ainsi que dans le domaine de la formation en matière d’estimations immobilières indépendantes.",
        section1Item2: "Nous sommes en mesure d’estimer tous les types de biens, que ce soit une maison d’habitation, un immeuble locatif, mixte, commercial ou administratif, un local artisanal, un terrain nu ou à mettre en valeur, une servitude, etc.",
        section1Item3: "Nous réalisons tout type d’expertises immobilières, qu’il s’agisse d’estimer une villa, un lot PPE, un immeuble, un bien-fonds non bâti, un droit de superficie ou encore d’autres droits réels et servitudes.",
        section1Item4: "La société, par l’intermédiaire de Mme Barbara Progin, est également active dans le domaine de la formation en estimations immobilières notamment à HEC Lausanne (3ème année bachelor management) et à l’USPI (brevet d’expert en estimation immobilière).",
        section1Item5: "Un travail indépendant étant primordial pour nous, la société ne participe à aucune activité de courtage ou de promotion, ce qui nous permet d’éviter les conflits d’intérêt et de garantir à nos clients une neutralité et une intégrité parfaites.",
        section2Title: "Rayon d’activité",
        section2Item1: "Nous réalisons des expertises immobilières indépendantes essentiellement en Suisse romande et plus particulièrement dans le canton de Vaud.",
        section2Item2: "Nous effectuons également des estimations immobilières plus ponctuelles dans les cantons du Valais, Berne, Neuchâtel et Fribourg.",
        image2: "./src/assets/images/Kitchen.jpg",
        imageDescription2: "Une cuisine moderne",
        namespace: "prestations",
    }
};