module.exports = {
    en: {
        image1: "./src/assets/images/TopBuildingCloseUp.jpg",
        imageDescription1: "Close-up of a modern building",
        image2: "./src/assets/images/BuildingWindowsCloseUp.jpg",
        imageDescription2: "Close-up of a building",
        title: "e2i-expertises",
        subTitle: "independent property valuations",
        section1Title: "Do you want to",
        section1Item1: "Learn the market value of a property for the purpose of purchase or a sale, inheritance, litigation or other purposes",
        section1Item2: "Assess the value of negotiating an easement",
        section1Item3: "Identify site development opportunities",
        section1Item4: "Estimate the value of a DDP",
        section1Item5: "Get help with condominium ownership (including propriété par étages law)",
        section1Item6: "Establish a fair rent",
        section1Item7: "Conduct periodic valuation of real estate",
        section1Item8: "get information, advice or support in any real estate matter?",
        section2Title: "Our expertise",
        section2Content: "Drawing on our expert knowledge and long experience, we can respond to all your questions and assist you in all your real estate business.<br><br>We are able to value all types of property, whether a house, an apartment building or vacant plot, and for any use, whether it be residential, commercial or mixed.",
        section3Title: "Customized service",
        section3Content: "We provide you with personalized information  to meet your needs.<br><br>We can conduct a range of valuation types, including market value, intrinsic value, yield value, DCF value, condominium (PPE) value, value per square meter, and residual value. We adapt our analysis to your type of property and your needs.",
        section4Title: "Independence",
        section4Content: "Our company is independent. We do not represent developers, or develop real estate ourselves. This allows us to avoid conflicts of interest and offer our customers neutrality and integrity.",
        namespace: "home",
    },
    fr: {
        image1: "./src/assets/images/TopBuildingCloseUp.jpg",
        imageDescription1: "Un immeuble moderne en gros plan",
        image2: "./src/assets/images/BuildingWindowsCloseUp.jpg",
        imageDescription2: "Un immeuble en gros plan",
        title: "e2i-expertises",
        subTitle: "expertises immobilières indépendantes",
        section1Title: "Vous souhaitez",
        section1Item1: "Connaître la valeur vénale d’un bien immobilier dans le cadre d’un achat ou d’une vente, d’une succession ou d’un partage, d’un litige, etc.",
        section1Item2: "Estimer la valeur de négociation d’une servitude",
        section1Item3: "Déterminer les possibilités de mise en valeur d’un terrain ou d’un site",
        section1Item4: "Déterminer la valeur d’un droit de superficie (DDP)",
        section1Item5: "Être soutenu dans la démarche de création d’une PPE",
        section1Item6: "Connaître le juste montant d’un loyer",
        section1Item7: "Procéder à l’évaluation périodique d’un parc immobilier",
        section1Item8: "disposer de tout renseignement, conseil ou soutien dans le domaine immobilier ?",
        section2Title: "Nos compétences",
        section2Content: "Nous mettons nos connaissances et notre savoir-faire à votre service pour apporter une réponse adéquate à vos interrogations et vous seconder dans toutes vos démarches en lien avec le domaine immobilier.<br><br>Nous sommes en mesure d’estimer tous les types de biens, que ce soit une maison d’habitation, un immeuble locatif, mixte, commercial ou administratif, un local artisanal, un terrain nu ou à mettre en valeur, une servitude, etc.",
        section3Title: "Du sur-mesure",
        section3Content: "Nous vous fournissons des études et des conseils personnalisés répondant aux spécificités de vos attentes.<br><br>Valeur vénale, valeur intrinsèque, valeur de rendement, valeur DCF, valeur PPE, valeur au m2, valeur résiduelle ? Nous adaptons notre analyse au type de bien et à vos objectifs afin de vous fournir un résultat pertinent en toute transparence.",
        section4Title: "En toute indépendance",
        section4Content: "Notre société agit en toute indépendance. Nous ne participons à aucune opération de courtage ou de promotion immobilière, ce qui nous permet d’éviter les conflits d’intérêt et de garantir à nos clients une neutralité et une intégrité parfaites.",
        namespace: "accueil",
    }
};