module.exports = {
    en: {
        title: "Links",
        Item1: "Chambre vaudoise immobilière",
        url1: "https://cvi.ch/",
        Item2: "Union suisse des professionnels de l’immobilier",
        url2: "https://www.uspi.ch/accueil/",
        Item3: "Chambre d’Experts Immobiliers",
        url3: "https://cei.ch/",
        Item4: "Association des notaires vaudois",
        url4: "https://www.notaires.ch/associations/vaud",
        Item5: "Guichet cartographique du canton de Vaud",
        url5: "https://www.geo.vd.ch/",
        Item6: "Etablissement Cantonal d’Assurance",
        url6: "https://www.eca-vaud.ch/",
        Item7: "Registre foncier Vaudois",
        url7: "https://www.vd.ch/index.php?id=1003327",
        namespace: "links",
    },
    fr: {
        title: "Liens",
        Item1: "Chambre vaudoise immobilière",
        url1: "https://cvi.ch/",
        Item2: "Union suisse des professionnels de l’immobilier",
        url2: "https://www.uspi.ch/accueil/",
        Item3: "Chambre d’Experts Immobiliers",
        url3: "https://cei.ch/",
        Item4: "Association des notaires vaudois",
        url4: "https://www.notaires.ch/associations/vaud",
        Item5: "Guichet cartographique du canton de Vaud",
        url5: "https://www.geo.vd.ch/",
        Item6: "Etablissement Cantonal d’Assurance",
        url6: "https://www.eca-vaud.ch/",
        Item7: "Registre foncier Vaudois",
        url7: "https://www.vd.ch/index.php?id=1003327",
        namespace: "links",
    }
};