module.exports = {
    en: {
        title: "Methodology",
        subTitle: "How we work, step by step:",
        section1Title: "1. The budget",
        section1Item1: "Based on a preliminary review of basic documents, we offer you a free estimate of our fees with no obligation.",
        section1Item2: "The documents you will be requested to provide for this step are:",
        section1ListItem1: "the land registry extract (extrait du registre foncier) – including PPE (condominium ownership) pages, if any",
        section1ListItem2: "a plan of the plot, showing the boundaries",
        section1ListItem3: "a copy of the insurance documents (police ECA) for all buildings",
        section1ListItem4: "For PPE work, a plan highlighting which condominiums are involved",
        section1ListItem5: "current tenancy arrangements, if any",
        section1Item3: "*Duration: one to two working days after receiving the necessary documents.",
        section2Title: "2. Site visit",
        section2Item1: "Upon acceptance of our quote, we will contact you to arrange a site visit.",
        section2Item2: "This step is essential for us to get a good sense of the property to be valued, and understand local factors that may bear on the valuation. A photographic record will be made during the visit.",
        section2Item3: "Some additional documents will be required from you at this time, depending on the type of property, in order to complete the file and proceed with the work",
        section2Item4: "*Duration: one to two hours on site for a standard property.",
        section3Title: "3. Analysis and production of report",
        section3Item1: "Our analysis is based on the documents that have been provided, the findings of the visit, as well as information that we have collected from different sources.",
        section3Item2: "We can conduct a large range of valuation types, including market value, intrinsic value, yield value, DCF value, condominium (PPE) value, value per square meter, and residual value depending on the type of property.",
        section3Item3: "The format of the report and type of analysis depends on the type of property and your requirements.",
        section3Item4: "*Duration: one to three weeks depending on the choosen report and on your requirements.",
        section3Item5: "*The duration of our work is only an indication. It can vary significantly depending on the complexity of the property to estimate, the type of report requested and our workload. In any case, we take into account  your situation in order to satisfy you the better way.",
        namespace: "methodologie",
    },
    fr: {
        title: "Méthodologie",
        subTitle: "Voici en quelques étapes notre manière de travailler.",
        section1Title: "1. Le devis",
        section1Item1: "Sur la base d’une première étude de quelques documents de base, nous sommes en mesure d’établir à votre attention un devis estimatif du montant de nos honoraires. Ce devis est gratuit et sans engagement.",
        section1Item2: "Les documents que vous serez amenés à nous fournir pour cette étape sont les suivants :",
        section1ListItem1: "l’extrait du registre foncier – y compris les feuillets pour les lots PPE,",
        section1ListItem2: "le plan cadastral de la parcelle,",
        section1ListItem3: "la copie de la police ECA pour tous les bâtiments, avec le détail des volumes,",
        section1ListItem4: "pour les lots PPE le plan teinté du ou des lots concernés.",
        section1ListItem5: "cas échéant l’état locatif à jour.",
        section1Item3: "*Durée: un à deux jours ouvrables dès réception de l’ensemble des document nécessaires.",
        section2Title: "2. La visite",
        section2Item1: "Après acceptation de notre devis, nous prenons contact avec vous afin d’organiser une visite des lieux.",
        section2Item2: "Cette étape est indispensable pour appréhender avec justesse le bien à évaluer et prendre le pouls de son environnement direct. Un dossier photographique est constitué lors de la visite.",
        section2Item3: "Certains documents supplémentaires vous sont demandés à cette occasion, en fonction du type de bien, ce afin de compléter le dossier et de pouvoir procéder à l’étude.",
        section2Item4: "*Durée: une à deux heures sur place pour un bien standard.",
        section3Title: "3. L’analyse et la production d’un rapport",
        section3Item1: "Notre analyse s’appuie sur les pièces qui nous ont été fournies, sur les constatations faites lors de la visite, ainsi que sur des informations que nous collecterons auprès de différentes instances.",
        section3Item2: "Nous faisons appel à toutes les techniques d’analyse courantes : valeur intrinsèque, valeur de rendement, valeur DCF, valeur PPE, valeur au m2, valeur résiduelle, etc. Les techniques sont choisies et mises en œuvre en fonction de leur opportunité, selon le contexte d’analyse et  le type de bien à étudier.",
        section3Item3: "La forme du rapport dépend du type de prestation que vous avez choisi.",
        section3Item4: "*Durée: une à trois semaines en fonction du rapport choisi et de vos exigences.",
        section3Item5: "*La durée de notre travail est donnée à titre indicatif. Elle peut varier sensiblement en fonction de la complexité du bien à estimer, du type de rapport demandé et de notre charge de travail. Dans tous les cas, nous tenons compte de l’urgence de votre situation pour vous satisfaire dans les meilleurs délais.",
        namespace: "methodologie",
    }
};