module.exports = {
    en: {
        title: "Our strengths",
        subTitle: "Market expertise, precise analysis and absolute discretion.",
        section1Title: "Expertise",
        section1ListItem1: "Excellent knowledge of the local market.",
        section1ListItem2: "Technical proficiency.",
        section1ListItem3: "Many years of experience in the field.",
        section1ListItem4: "Advanced training in the field regularly updated through continuous training.",
        section2Title: "Independence",
        section2ListItem1: "No participation in any commercial real estate transactions.",
        section2ListItem2: "Absence of conflicts of interest.",
        section2ListItem3: "Complete impartiality to ensure our clients neutral analysis.",
        section3Title: "Attention to client needs",
        section3ListItem1: "Customized solutions according to your needs and your budget.",
        section3ListItem2: "Advanced analytical tools depending on your situation.",
        section4Title: "Discretion",
        section4ListItem1: "Absolute discretion.",
        section4ListItem2: "Privacy and data protection.",
        section4ListItem3: "Rigor of our work.",
        namespace: "our-strengths",
    },
    fr: {
        title: "Points forts",
        subTitle: "Maîtrise du marché, des analyses précises et une discrétion absolue.",
        section1Title: "Compétences et expertises",
        section1ListItem1: "Excellente connaissance du marché local.",
        section1ListItem2: "Maîtrise de l’ensemble des techniques d’analyse courante.",
        section1ListItem3: "Nombreuses années d’expérience dans le métier.",
        section1ListItem4: "Formation poussée dans le domaine régulièrement mises à jour par le biais de formations continues.",
        section2Title: "Indépendance",
        section2ListItem1: "Aucune participation à de quelconques opérations immobilières commerciales.",
        section2ListItem2: "Absence de conflits d’intérêts.",
        section2ListItem3: "Préservation d’une impartialité totale afin de garantir à notre clientèle des analyses neutres, qui ne sont entachées d’aucun a priori ou intérêt particulier.",
        section3Title: "Ecoute",
        section3ListItem1: "Des solutions personnalisées en fonction de vos besoins et de votre budget.",
        section3ListItem2: "Des outils d’analyse pointus et différenciés en fonction de votre situation.",
        section4Title: "Discrétion",
        section4ListItem1: "Discrétion absolue.",
        section4ListItem2: "Confidentialité et protection de vos données.",
        section4ListItem3: "Rigueur de notre travail.",
        namespace: "points-forts",
    }
};