module.exports = {
    en: {
        image: "./src/assets/images/BuildingCloseUp.jpg",
        imageDescription: "Close-up of a modern building",
        title: "Services",
        subTitle: "Our company offers services tailored to your needs.",
        section1Title: "Our services",
        section1Item1: "Value estimation of properties (villas, apartments, PPE, residential buildings, commercial and industrial buildings, vacant land, etc.).",
        section1Item2: "Various real estate advice.",
        section1Item3: "Value estimation of real rights (prohibition / restriction of building rights, build easements, rights of way, DDP, etc.).",
        section1Item4: "Real estate appraisal training.",
        section1Item5: "Advice and assistance for purchasing or selling a property.",
        section1Item6: "Advice for the creation and management of PPE buildings.",
        section2Title: "Types of reports",
        section2Content1: "We offer several report formats at varying levels of detail. We will help you choose the right format, based on the context and complexity of the work, and your own requirements<br><br>Thus, we offer you the opportunity to choose between two types of services:",
        section2listItem1: "Full appraisal reports",
        section2listItem2: "More succinct property advices",
        section2Content2: "We would like to fulfill your needs in the best way by helping you to choose the report type which is the most appropriate to your situation.",
        section3Title: "Our fees",
        section3Content: "We charge  our services based on the time required to complete the work on an hourly basis of fr. 150.- to 200.-.<br><br>This can vary greatly, depending on the complexity of the task and client expectations. Before starting work, we always offer a free quotation with no obligation, so you can make a considered decision.<br><br>Various illustrative quotation examples are presented under our FAQ section.",
        namespace: "services",
    },
    fr: {
        image: "./src/assets/images/BuildingCloseUp.jpg",
        imageDescription: "Un immeuble moderne en gros plan",
        title: "Prestations",
        subTitle: "Notre société vous propose des prestations sur mesure répondant à vos attentes et vos besoins particuliers.",
        section1Title: "Prestations offertes",
        section1Item1: "Estimation de la valeur de tout type de biens immobiliers (villas, appartements, lots PPE, immeubles, bâtiments commerciaux ou industriels, terrains nus, etc.).",
        section1Item2: "Conseils immobiliers divers.",
        section1Item3: "Estimation de la valeur de tout type de droits réels (servitudes d’interdiction/restriction de bâtir, servitudes de passage, DDP, etc.).",
        section1Item4: "Formation dans le domaine de l’expertise immobilière indépendante.",
        section1Item5: "Conseil et assistance lors de l’achat et de la vente d’un bien immobilier.",
        section1Item6: "Conseil à la création et à la gestion de PPE.",
        section2Title: "Types de rapports",
        section2Content1: "En fonction de vos objectifs, du contexte et du degré de complexité de l’étude, nous vous proposons différents types de services, qui se différencient par le degré de finesse de l’analyse et des détails fournis dans les rapports.<br><br>Ainsi, nous vous offrons la possibilité de choisir entre deux types de produit:",
        section2listItem1: "Des rapports d’expertises complets",
        section2listItem2: "Des conseils immobiliers plus succincts",
        section2Content2: "Notre volonté étant de satisfaire au mieux vos besoins, nous essayons toujours de vous orienter sur le type de rapport le plus approprié à votre situation.",
        section3Title: "Coût de nos prestations",
        section3Content: "Nous facturons nos prestations en fonction du temps nécessaire pour mener à bien notre mandat sur la base d’un tarif horaire moyen allant de fr. 150 à fr. 200.- suivant les prestations.<br><br>Le travail à fournir peut considérablement varier suivant la complexité de la situation et les attentes de nos mandants. C’est pourquoi nous établissons avant toute analyse un devis gratuit et sans engagement pour nos travaux futurs, afin que vous puissiez prendre une décision en toute connaissance de cause.<br><br>Des exemples indicatifs de devis vous sont présentés sous notre rubrique FAQ.",
        namespace: "prestations",
    }
};