module.exports = {
    en: {
        image: "./src/assets/images/PortraitBarbaraProgin.jpg",
        imageDescription: "Portrait of founder and director Barbara Progin.",
        title: "Team",
        subTitle: "Barbara Progin<br>T. +41 21 647 59 60<br>barbara.progin@<br>e2i-expertises.ch",
        section1Title: "Professional skills",
        section1ListItem1: "Fondatrice et directrice de la société E2i expertises immobilières indépendantes sàrl.",
        section1ListItem2: "Diplôme postgrade de l’Institut d’Etudes Immobilières, à Genève.",
        section1ListItem3: "Master à HEC Lausanne.",
        section2Title: "Activity",
        section2ListItem1: "Vice-president of the “Commission Cantonale Immobilière” (CCI)",
        section2ListItem2: "Lecturer of real estate appraisal at HEC Lausanne.",
        section2ListItem3: "Lecturer at “USPI formation” (federal certificate of real estate appraiser).",
        section2ListItem4: 'Member of the "Chambre des experts en estimations immobilières" (CEI) and the "Schweizer Immobilienschätzer-Verband" (SIV)',
        section3Title: "Languages",
        section3ListItem1: "French",
        section3ListItem2: "English",
        section3ListItem3: "German",
        namespace: "team",
    },
    fr: {
        image: "./src/assets/images/PortraitBarbaraProgin.jpg",
        imageDescription: "Portrait de la fondatrice et directrice Barbara Progin.",
        title: "Qui suis-je",
        subTitle: "Barbara Progin<br>T. +41 21 647 59 60<br>barbara.progin@<br>e2i-expertises.ch",
        section1Title: "Expériences",
        section1ListItem1: "Fondatrice et directrice de la société E2i expertises immobilières indépendantes sàrl.",
        section1ListItem2: "Diplôme postgrade de l’Institut d’Etudes Immobilières, à Genève.",
        section1ListItem3: "Master à HEC Lausanne.",
        section2Title: "Activités",
        section2ListItem1: "Vice-présidente de la commission cantonale immobilière (CCI, Etat de Vaud).",
        section2ListItem2: "Chargée de cours  d’expertise immobilière à HEC Lausanne.",
        section2ListItem3: "Professeur auprès de l’USPI formation (brevet fédéral d’expert).",
        section2ListItem4: "Membre de la chambre des experts en estimations immobilières (CEI) et de la Schweizer Immobilienschätzer-Verband (SIV).",
        section3Title: "Langues",
        section3ListItem1: "Français",
        section3ListItem2: "Anglais",
        section3ListItem3: "Allemand",
        namespace: "qui-suis-je",
    }
};